### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Alex7Lem** [techdivision/import-category#40]
Good afternoon!

Please tell me how to install the import-category module.

With the use of these commands, nothing happens:
composer config repositories.techdivision git https://github.com/techdivision/import-category
composer require techdivision/import-category

Thanks in advance

**Comment by wagnert** [comment]
Hi, you've to install the [CLI Tool](https://www.github.com/techdivision/import-cli-simple), this repository is only a library that doesn't run standalone.
