### ISSUE TITLE
import creates URL rewrites for store views that don't contain the category

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-category#50]
## Prerequisites:
* Magento 2.3
* PHP 7.2
* `composer require techdivision/import-cli-simple:3.1.0-beta9`
* at least 2 websites (within the same Magento installation), say website A and website B
* a number of store views `a_1, ..., a_m` in website A and `b_1, ..., b_n` in website B
* a category X in website A and a category Y in website B, such that X and Y have the same URL keys

## Expected behaviour:
When importing the categories A and B via M2IF the import should create URL rewrites for category A in the store views `a_1, ..., a_m`. And it should create URL rewrites for category B in the store views `b_1, ..., b_n`. That way there is no conflict with A and B having the same URL key.

## Actual behaviour:
When importing the categories A (first) and B (second), the import first creates URL rewrites for A in all store views (`a_1, ..., a_m, b_1, ..., b_n`). Then it tries to create the rewrites for the category B and a integrity constraint exception is thrown.

## Code details:
The problem lies in the class `TechDivision\Import\Category\Observers\CategoryUrlRewriteObserver` in the `process()` method. When preparing the URL rewrite data for the `admin` store view, all available store views are prepared instead of only those that have the correct root category (`if ($storeViewCode === StoreViewCodes::ADMIN) {` and the following lines).

I did some debugging and tried to find a fix myself, but since we're a bit pressed to get those imports working, I opted for a workaround instead. Let me know if you have any questions.

**Comment by ktruehl** [comment]
So. I have become a bit more familiar with the M2IF framework, and I have written my own workaround for this. The crucial point is to return the right store view codes for the current category.

I extended the `EeBuchProcessor`
```
class EeBunchSubject extends \TechDivision\Import\Category\Ee\Subjects\EeBunchSubject
{
    /**
     * returns the store view codes relevant to the category represented by the current row
     *
     * @return array
     * @throws \Exception
     */
    public function getRootCategoryStoreViewCodes()
    {
        $path = $this->getValue(\TechDivision\Import\Category\Utils\ColumnKeys::PATH);
        $rootCategoryPath = explode('/', $path)[0];
        $rootCategory = $this->getCategoryByPath($rootCategoryPath);

        $storeCodes = [];
        foreach ($this->rootCategories as $storeCode => $category)
        {
            if ($category['entity_id'] == $rootCategory['entity_id'])
                $storeCodes[] = $storeCode;
        }
        return $storeCodes;
    }
}
```
and then the `CategoryUrlRewriteObserver`:
```
class CategoryUrlRewriteObserver extends \TechDivision\Import\Category\Observers\CategoryUrlRewriteObserver
{

    /**
     * @inheritdoc
     *
     * makes sure only the relevant store view codes are returned
     *
     * @return array
     * @throws \Exception
     */
    protected function getStoreViewCodes()
    {
        $subject = $this->getSubject();
        /* @var \Lehner\PimCategoriesImport\Import\Subjects\EeBunchSubject $subject */
        return $subject->getRootCategoryStoreViewCodes();
    }
}
```

**Comment by wagnert** [comment]
Hi, it would be really nice if you would create a PR with your workaround/bugfix ... is that possible?

**Comment by ktruehl** [comment]
I'll try to get to it as soon as possible.

**Comment by ktruehl** [comment]
Voilà the pull request. I didn't test it outside the context of our client's setup. Just copied over the code.
