### ISSUE TITLE
UrlRewriteUpdateObserver uses wrong delete method on bunch processor

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-category#51]
## Prerequisites:
* Magento 2.3
* PHP 7.2
* `composer require techdivision/import-cli-simple:3.1.0-beta9`

## Description
In `TechDivision\Import\Category\Observers\UrlRewriteUpdateObserver` in the `deleteUrlRewrite()` method, the wrong method `removeUrlRewrite()` is called on the bunch processor `TechDivision\Import\Category\ServicesCategoryBunchProcessor`. Instead of `removeUrlRewrite()` the method is called `deleteUrlRewrite()`.

**Comment by wagnert** [comment]
Hi, we'll fix that with the next release, thanks for reporting :)

**Comment by wagnert** [comment]
@ktruehl This has been closed with https://github.com/techdivision/import-category/commit/526f578155af250981b5a175bf916f41e35fe3ff
