### ISSUE TITLE
Import of Category URL rewrites does not work

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-category#52]
## Prerequisites:
* Magento 2.3
* PHP 7.2
* `composer require techdivision/import-cli-simple:3.1.0-beta9`

## Description:
In `TechDivision\Import\Category\Observers\UrlRewriteUpdateObserver` the `process()` method has a number of problems:

The lines
```
        foreach ($this->existingUrlRewrites as $existingUrlRewrites) {
            foreach ($existingUrlRewrites as $existingUrlRewrite) {
```
first loop over the URL rewrites rows and then over the columns.

Within the loop the rewrite data does not set the `is_autogenerated` field:
```
                    $attr = array(
                        MemberNames::REDIRECT_TYPE    => 301,
                        MemberNames::TARGET_PATH      => $targetPath,
                    );
```
The problem here is that the Magento (at least as of EE 2.3) loads category collections by joining the URL rewrites table and filtering by `is_autogenerated = 1` instead  of filterung by the redirect type. So when a 301-redirect is created that has `is_autogenerated = 1` set, the collection loads the same category twice with two different URL rewrites joined. An exception is thrown. Something like "Item with ID ?? alread exists in collection".

I created a patch for this. 
[bugfix-[5.x]-fix-url-rewrite-update.diff.zip](https://github.com/techdivision/import-category/files/2828483/bugfix-.5.x.-fix-url-rewrite-update.diff.zip)

## Functionality

There is also the problem with th`UrlRewriteUpdateObserver` handles rewrites. It doesn't resolve transitive URL rewrites. And as such it does not handle rewrite loops correctly. I modified the implementation of the `UrlRewriteUpdateObserver` to handle this.
```
class UrlRewriteUpdateObserver extends \TechDivision\Import\Category\Observers\UrlRewriteUpdateObserver
{
    protected function process()
    {
        if ($this->getSubject()->getConfiguration()->hasParam(\TechDivision\Import\Category\Utils\ConfigurationKeys::CLEAN_UP_URL_REWRITES) &&
            !$this->getSubject()->getCoreConfigData(\TechDivision\Import\Category\Utils\CoreConfigDataKeys::CATALOG_SEO_SAVE_REWRITES_HISTORY, true))
        {
            // in our client's case we don't have to deal with this case
            parent::process();
            return;
        }

        // since we have our own implementation for this case, we skip the implementation in the immediate
        // parent class
        \TechDivision\Import\Category\Observers\UrlRewriteObserver::process();

        // get new target path for the current category
        $newTargetPath = $this->prepareRequestPath();

        // create redirect URL rewrites for the existing URL rewrites and save the old target path, if any
        $oldTargetPath = null;
        foreach ($this->existingUrlRewrites as $existingUrlRewrite)
        {
            if ($existingUrlRewrite[MemberNames::REDIRECT_TYPE] == 0)
            {
                // in this case, this is the previous main rewrite with
                $oldTargetPath = $existingUrlRewrite[MemberNames::REQUEST_PATH];
            }
            else
            {
                // nothing do to for redirect_type!=0 if the target path is alredy correct
                if ($existingUrlRewrite[MemberNames::TARGET_PATH] === $newTargetPath)
                    continue;
            }

            // if updating the existing URL rewrite would create an identity rewrite, the existing URL rewrite
            // has to be deleted
            if ($existingUrlRewrite[MemberNames::REQUEST_PATH] === $newTargetPath)
            {
                $this->deleteUrlRewrite([
                    'url_rewrite_id' => $existingUrlRewrite[MemberNames::URL_REWRITE_ID]
                ]);
                continue;
            }

            // override data with the 301 configuration
            $attr = array(
                MemberNames::REDIRECT_TYPE    => 301,
                MemberNames::TARGET_PATH      => $newTargetPath,
                MemberNames::IS_AUTOGENERATED => 0
            );
            // is_autogenerated=0 is necessary, since Magento 2 handles category collections in a weird way:
            // instead of searching for redirect_type=0 it filters by is_autogenerated=1

            // merge and return the prepared URL rewrite
            $existingUrlRewrite = $this->mergeEntity($existingUrlRewrite, $attr);

            // create the URL rewrite
            $this->persistUrlRewrite($existingUrlRewrite);
        }
    }

    protected function initializeUrlRewrite(array $attr)
    {
        // iterate over the available URL rewrites to find the one that matches the request path, if any
        foreach ($this->existingUrlRewrites as $urlRewrite)
        {
            // if the request path matches, this rewrite has to be the new main rewrite (i.e. redirect_type=0)
            if ($urlRewrite[MemberNames::REQUEST_PATH] === $attr[MemberNames::REQUEST_PATH])
            {
                // make sure it is not processed any further after inserting
                $this->removeExistingUrlRewrite($urlRewrite);
                return $this->mergeEntity($urlRewrite, $attr);
            }
        }

        // simple return the attributes, so that a new rewrite is created
        return $attr;
    }
}
```

**Comment by wagnert** [comment]
Thank's we'll have a look at it soon :)

**Comment by wagnert** [comment]
Hi, i had a look at it today and think that you're absolutely right. There are some issues and a major refactoring is necessary to solve them. I'll need some days for that. I'll keep you updated!

**Comment by ktruehl** [comment]
Great. Thanks. I would implement this in a more general way (i.e. not specifically for the use-case of our client) and create a pull request, but I just don't have time (at least not for now). I'm afraid you will hear quite a lot from me in the next few weeks. 😉

**Comment by wagnert** [comment]
You're welcome, i'm happy to see that you're using M2IF as well as we did in our projects. So i'm thankful for any issues you report and will try to fix them as soon as possible.

**Comment by wagnert** [comment]
@ktruehl I've fixed the issues you described under "Description", but i didn't really understand the problem you described in "Functionality". Can you please give me a more detailed description what you mean with transitive URLs, in best case an example, so that i can reproduce the issue.

**Comment by ktruehl** [comment]
Say you have a category with url path `stuff`. Then you should have one rewrite:
1) from `stuff/` to `catalog/category/view/id/xxx` with `redirect_type=0`.

Now change the url key to `stuff-blub`, then you should get 2 rewrites:
1) from `stuff-blub/` to  `catalog/category/view/id/xxx` with `redirect_type=0` and
2) from `stuff/` to `stuff-blub/` with `redirect_type=301`.

Now change the url key again to `stuff-whee`, then the result without resolving transitivity would be:
1) from `stuff-whee/` to  `catalog/category/view/id/xxx` with `redirect_type=0`,
2) from `stuff/` to `stuff-blub/` with `redirect_type=301` and
3) from `stuff-blub/` to `stuff-whee/`  with `redirect_type=301`.

Now, if you change back the URL key to `stuff`, you get
1) from `stuff/` to  `catalog/category/view/id/xxx` with `redirect_type=0`,
3) from `stuff-blub/` to `stuff-whee/`  with `redirect_type=301` and 
4) from `stuff-whee/` to `stuff/`  with `redirect_type=301`.

I was wrong in assuming that loops could occur by not resolving transitivity. So there is no problem as such. However, my implementation in addition resolves the transitivity and the result in this case would be:
1) from `stuff/` to  `catalog/category/view/id/xxx` with `redirect_type=0`,
3) from `stuff-blub/` to `stuff/`  with `redirect_type=301` and 
4) from `stuff-whee/` to `stuff/`  with `redirect_type=301`.

Here all 301 rewrites point to the request path of the one URL rewrite with `redirect_type=0`. It makes it look tidier and maybe more performant when visiting `/stuff-blub/`, but it's not strictly necessary.

**Comment by wagnert** [comment]
@ktruehl Thanks for your explanation. I'll check that and refactor the actual implementation where necessary. Thanks again for reporting and your time, we appreciate that very much.

**Comment by wagnert** [comment]
@ktruehl I've added a bugfix in the 6.x branch. If you'll find the time, it'll be awesome if you could make a test run. In my local testing environment (2.3.0 CE) it'll works as expected.

**Comment by wagnert** [comment]
@ktruehl This has been closed with https://github.com/techdivision/import-category/commit/526f578155af250981b5a175bf916f41e35fe3ff.

**Comment by ktruehl** [comment]
Thanks for the fix. I'l upgrade to the latest version once I have the category import running on our side. Then I will test it again and let you know if I find something.

**Comment by wagnert** [comment]
You're welcome @ktruehl. Looking forward to hear from you :-)

**Comment by ktruehl** [comment]
OK. So after finishing the category import for our client I updated the M2IF, and I finally managed to test this. It seems to work nicely, now. It doesn't yet transitively resolve rewrites but that is more a question of taste (and maybe performance) than that of functionality:
```
k-bettwaren/bettwaesche-whee/tommy-hilfiger/ -> k-bettwaren/bettwaesche/tommy-hilfiger/ (301)
k-bettwaren/bettwaesche-blub/tommy-hilfiger/ -> k-bettwaren/bettwaesche-whee/tommy-hilfiger/ (301)
k-bettwaren/bettwaesche/tommy-hilfiger/ -> catalog/category/view/id/227505588 (0)
```

Thanks a lot for fixing this.
