### ISSUE TITLE
UrlKeyAndPathObserver creates wrong URL path for non-admin store views

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-category#55]
## Prerequisites:
* Magento 2.3
* PHP 7.2
* `composer require techdivision/import-cli-simple:3.1.0-beta9`
* At least 2 store views `A` and `B` within the same website, such that the categories in store view `A` inherit the URL keys from the `admin` store view and the categories in store view B have different URL keys to the ones in `admin` and `A`. This happens naturally if A and B represent different languages.

## Description
In `TechDivision\Import\Category\Observers\UrlKeyAndPathObserver` in the `process()` method, the URL path is put together by taking the URL key from the current row and the stored URL path from the existing parent category (`$existingCategory[MemberNames::URL_KEY]`). The problem is that `$existingCategory = $this->getCategoryByPath($categoryPath)` contains only the values for the admin store. So, if the categories in store view `A` inherit the URL keys from `admin`, then the URL keys for store view `A` are created correctly. But
* if the categories in store view `B` have different URL keys from the ones in `admin`,
* and if category `Y` has parent category `X`,
* and if the URL paths of `X` differ in `admin` and `B`,

then the URL path that is created for `Y` in `B` will consist of the URL path of `X` from `admin` and the URL key of `Y` from `B`, which is not correct.

**Comment by wagnert** [comment]
@ktruehl Is it possible give me an example of your CSV file? It'll help if i can get impression how it look like.

**Comment by wagnert** [comment]
@ktruehl Doesn't need it anymore, created my own one and see the problem, thanks :)

**Comment by wagnert** [comment]
@ktruehl Seems that i've some additional problems with multiple store views. I think i've found a solution, but i need at least one more day to test the new stuff, sorry for delay :-(

**Comment by wagnert** [comment]
@ktruehl Fixed this with version [3.1.0-beta13](https://github.com/techdivision/import-cli-simple/releases/tag/3.1.0-beta13). It would be nice if you'll find the time to test it, as major changes has been necessary to make it work :-( If there still are any issues feel free to re-open the issue. Please be aware that you've to make changes to your configuration as described [here](https://github.com/techdivision/import-cli-simple/blob/3.1.x/UPGRADE-3.1.0.md).

**Comment by ktruehl** [comment]
I'll have a look at it as soon as possible.

**Comment by ktruehl** [comment]
I updated the M2IF and did a quick test run. Everything seems to work.

**Comment by wagnert** [comment]
Perfect, thanks for testing 👍
