### ISSUE TITLE
CategoryUrlRewriteObserver can't handle renamed categories

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-category#56]
## Prerequisites:
* Magento 2.3
* PHP 7.2
* `composer require techdivision/import-cli-simple:3.1.0-beta9`
* Categories are uniquely identifiable by some external ID, as might be coming from a PIM.
* The shop contains category `A` with Name "Blub".
* The import file contains the same category `A` but with changed name "Whee".

## Description
If categories have some unique external ID coming from a PIM and if we use the category import to continuously update the categories, then the case might arrise that a category changes its name. In our case we have some kind of mapper, which takes the data from the PIM and translates it into a CSV format, which the M2IF category import can understand. So, if category `A` changes its name from "Blub" to "Whee", we have to include the old name path "[parent category name path]/Blub" in the created CSV file. But in the same row the CSV file will contain the new name "Whee" for the category.

Now the following happens:
1. In `TechDivision\Import\Category\Observers\CategoryUrlRewriteObserver` the URL rewrites are written to a new CSV file with prefix `url-rewrite`. For category `A` the URL path "[parent category name path]/Blub" will be written together with the URL rewrites to allow identifying the category at a later point.
2. In the Subject that contains the UrlRewriteUpdateObserver, the categories will be loaded again from the database. The `$categories` property in `TechDivision\Import\Category\Subjects\AbstractCategorySubject` will then contain the data of the categories referenced by their name path as it is currently stored in the database. In particular, category `A` will be referenced by the name path  "[parent category name path]/Whee", which contains the new name.
3. Now `TechDivision\Import\Category\Observers\UrlRewriteUpdateObserver` process the CSV file with prefix `url-rewrite`, in which category `A` is still referenced with the old name path "[parent category name path]/Blub". So when the observer tries to get the data for the category `A`, it will use the old name path. Then the method `getCategoryByPath()` in `TechDivision\Import\Category\Subjects\AbstractCategorySubject` cannot find the category and throws an exception.

**Comment by ktruehl** [comment]
I forgot to post my solution (more hack than workaround) to this. I overwrote the method `getValue()` in `TechDivision\Import\Category\Observers\CategoryUrlRewriteObserver` by the following implementation:
```
    public function getValue($name, $default = null, callable $callback = null)
    {
        if ($name === ColumnKeys::PATH)
        {
            $pathArray = explode('/', parent::getValue($name, $default, $callback));
            $pathArray[count($pathArray) - 1] = parent::getValue(ColumnKeys::NAME);
            return implode('/', $pathArray);
        }

        return parent::getValue($name, $default, $callback);
    }
```

**Comment by wagnert** [comment]
@ktruehl Am i correct, when i assume, that you ONLY changed the value in the column `name`, not the value in the column `path`? The value `path` is comparable with the SKU of a product, which means when the path changes a new product will be created.

**Comment by wagnert** [comment]
@ktruehl I think the issue has been closed with [3.1.0-beta13](https://github.com/techdivision/import-cli-simple/releases/tag/3.1.0-beta13). If not, or my assumption in the comment above has been wrong, please re-open the issue.

**Comment by ktruehl** [comment]
Yeah, I do see the point about uniqueness of path. In the end it's a philosophical question. My workaround works and is simple enough, so that should be fine.

Concerning the major changes you did: Does that mean that I now have to provide the name path in the correct language for each store view? Currently I'm simply using the name path from the admin store to identify a category for each store view.

**Comment by wagnert** [comment]
Hi, especially in the case of categories it is. I think Magento knows why they didn't implement a category import ;)

The `path` column is the unique identifier and the `name` column is used to be render the category tree in backend and the categories in frontend, for example the file i've tested it with looks like the following 

<img width="1402" alt="category-csv" src="https://user-images.githubusercontent.com/287509/53555495-574c2880-3b42-11e9-8e6b-51b214e32e0c.png">

**Comment by ktruehl** [comment]
Great. Thanks for the info. Then it should still work for me.
