### ISSUE TITLE
Incorrect rename of url_key

### ISSUE THREAD

**Issue by gregordonsky** [techdivision/import-category#62]
Hi Tim,

I have a problem with categories that shares the same url_key but have a different url_path

### Prerequisites:
1. Magento 2.3.4
2. PHP 7.3
3. import-cli-simple 3.8.7

### Description:

I think that is legit to have the same url_key for categories that have a different url_path.

For example if i have these categories:

Path | Url Key | Expected Url Path
------------ | ------------- | -------------
Default Category/Linee | linee | linee
Default Category/Stili | stili | stili
Default Category/Linee/All Ready | all-ready | linee/all-ready
Default Category/Stili/All Ready | all-ready | stili/all-ready

The url key in the last line is automatically converted.
This happens because the import process does not allow to duplicate url_key and doesn't take into consideration the real url_path of the categories.

The conversion is done at these lines:
https://github.com/techdivision/import-category/blob/932698171e50f9f4696c048a30d7f5191e47148d/src/Observers/UrlKeyAndPathObserver.php#L106
https://github.com/techdivision/import-category/blob/932698171e50f9f4696c048a30d7f5191e47148d/src/Observers/UrlKeyAndPathObserver.php#L110

and it is done before the url_path is calculated.
Unfortunatly i didn't find a rapid solution so i removed $this->makeUnique for now.

Thanks in advance

**Comment by wagnert** [comment]
@gregordonsky We're already working on that issue, thanks for reporting :)
