### ISSUE TITLE
Position is set to 0

### ISSUE THREAD

**Issue by amenk** [techdivision/import-category#64]
When importing the attached file, the leads to `catalog_category_entity.position` being zero. It happens for all categories. So if multiple categories are imported, they all don't have position information.

As a side effect it is no longer possible to reorder those categories in the admin panel via drag'n'drop.

Most recent import version; Magento version 2.3.4-p2 CE

[category-import_20200714_1.zip](https://github.com/techdivision/import-category/files/4951496/category-import_20200714_1.zip)

![image](https://user-images.githubusercontent.com/1087128/88016688-41b71480-cb24-11ea-9335-3e7895136623.png)

**Comment by wagnert** [comment]
@amenk We'll check this as soon as possible and come back to you :-)

**Comment by wagnert** [comment]
@amenk That weird indeed. The problem seems to be the initial import that set's the zero values. After that, the sorting by drag-n-drop in the Admin seems to have a problem, because the other values that have zero as position overwrite the value 1.  Specifying the position at the first import and have it blank for the updates doesn't override the positions that has been configured by drag-n-drop in the Admin then. I'll add a ticket and we'll fix it as soon as possible.

**Comment by amenk** [comment]
@wagnert Were you able to reproduce this? It would be a big hassle to need to generate the positions I think ... is there support to auto-position the newly created categories based on the order in the CSV?

**Comment by amenk** [comment]
after rethinking about it, I think it is indeed better if we generate the positions, so an updated category tree will be reflected properly.

**Comment by wagnert** [comment]
Hi @amenk, this would be an appropriate solution for sure. But in general, I think we should create default values that don't deactive the backend drag-n-drop functionality.

**Comment by amenk** [comment]
@wagnert is there any logic happening in m2if for positions? I observed, that the imported position not necessarily correspond to what ends up in the database.

But I might have had some strange data, because I wasn't using the serializer to implode paths (and had / and " in the path) ... after using that, it seems to be more consistent.

**Comment by amenk** [comment]
But even with correct imploding / escaping, something seems to happen to the positions during the import

**Comment by amenk** [comment]
> But even with correct imploding / escaping, something seems to happen to the positions during the import


that is fixed now in the latest version 3.8.25, thanks @wagnert
