### ISSUE TITLE
getAttributeSetNameById called on null

### ISSUE THREAD

**Issue by amenk** [techdivision/import-category#68]
I have only specified include_in_menu in the default file and upgraded to 4.0.0-alpha1

	{
	    "default-values": {
		"catalog_category": {
		    "include_in_menu": null
		}
	    }
	}

And I am getting

	 Uncaught TypeError: Argument 1 passed to TechDivision\Import\Category\Listeners\SortCategoryListener::getAttributeSetNameById() must be of the type integer, null given, called in /home/example/example/projects/shop.example.com/vendor/techdivision/import-category/src/Listeners/SortCategoryListener.php on line 377 and defined in /home/example/example/projects/shop.example.com/vendor/techdivision/import-category/src/Listeners/SortCategoryListener.php:396
	Stack trace:
	#0 /home/example/example/projects/shop.example.com/vendor/techdivision/import-category/src/Listeners/SortCategoryListener.php(377): TechDivision\Import\Category\Listeners\SortCategoryListener->getAttributeSetNameById(NULL)
	#1 /home/example/example/projects/shop.example.com/vendor/techdivision/import-category/src/Listeners/SortCategoryListener.php(176): TechDivision\Import\Category\Listeners\SortCategoryListener->update('Root/Produkte/S...', Array)
	#2 [internal function]: TechDivision\Import\Category\Listeners\SortCategoryListener->handle(Object(League\Event\Event), Object(TechDivision\Import\ 

might that be related / is something wrong with the defaults?

_Originally posted by @amenk in https://github.com/techdivision/import-category/issues/66#issuecomment-685541321_

**Comment by amenk** [comment]
We do not have `attribute_set_id` in the CSV (attribute_set_code *is* set in the CSV) columns and there is this code:

https://github.com/techdivision/import-category/blob/975266a0aa4410de417d9664f04229a9e6d5c0f4/src/Listeners/SortCategoryListener.php#L377

This was introduced in the fix for https://github.com/techdivision/import-category/issues/64

@wagnert

**Comment by amenk** [comment]
see https://github.com/techdivision/import-category/issues/66#issuecomment-685664793
/assign wagnert

**Comment by amenk** [comment]
I can confirm this works - please ping me when it is released

**Comment by amenk** [comment]
@wagnert is this already released?

**Comment by wagnert** [comment]
@amenk Not yet, but I can create a new version 4.0.0-alpha2 today :)
