### ISSUE TITLE
Undefined index: techdivision_import_utils_entityStatus_memberName (4.0.0-alpha.2)

### ISSUE THREAD

**Issue by amenk** [techdivision/import-category#69]
getting this error in 4.0.0-alpha2

	PHP Notice:  Undefined index: techdivision_import_utils_entityStatus_memberName in /home/user/example/projects/shop.example.com/vendor/techdivision/import/src/Actions/GenericIdentifierAction.php on line 51
		PHP Fatal error:  Uncaught Error: Method name must be a string in /home/user/example/projects/shop.example.com/vendor/techdivision/import/src/Actions/GenericIdentifierAction.php:54
		Stack trace:
		#0 /home/user/example/projects/shop.example.com/vendor/techdivision/import-category/src/Services/CategoryBunchProcessor.php(1058): TechDivision\Import\Actions\GenericIdentifierAction->persist(Array, NULL)
		#1 /home/user/example/projects/shop.example.com/vendor/techdivision/import-category/src/Observers/CategoryObserver.php(411): TechDivision\Import\Category\Services\CategoryBunchProcessor->persistCategory(Array)
		#2 /home/user/example/projects/shop.example.com/vendor/techdivision/import-category/src/Observers/CategoryObserver.php(165): TechDivision\Import\Category\Observers\CategoryObserver->persistCategory(Array)
		#3 /home/user/example/projects/shop.example.com/vendor/techdivision/import-category/src/Observers/AbstractCategoryImportObserver.php(54): TechDivision\Import\Category\Observers\CategoryObserver->process()

Command

     vendor/bin/import-simple import:create:ok-file &&  vendor/bin/import-simple import:categories --debug-mode=1 --clear-artefacts=0 --log-level=warning

I will provide the CSV privately

**Comment by amenk** [comment]
![test-testing-step_015](https://user-images.githubusercontent.com/1087128/92747248-4bbafe00-f384-11ea-9ca3-6be197f9ce61.png)

Debugging ... Category seems to be empty in my case for some reason

**Comment by amenk** [comment]
It fails getting the root category "1" .. via n98-magerun2 dev:console I can get it

	>>> $cr =  $di->get(\Magento\Catalog\Model\CategoryRepository::class);
	=> Magento\Catalog\Model\CategoryRepository\Interceptor {#24166}
	>>> $cr->get(1)->debug();
	=> [
	     "entity_id" => "1",
	     "attribute_set_id" => "3",
	     "parent_id" => "0",
	     "created_at" => "2017-05-29 17:35:16",
	     "updated_at" => "2020-09-10 09:54:04",
	     "path" => "1",
	     "position" => "0",
	     "level" => "0",
	     "children_count" => "266",
	     "name" => "Root Catalog",
	     "include_in_menu" => "1",
	     "use_name_in_product_search" => "1",
	     "virtual_rule (Smile\ElasticsuiteVirtualCategory\Model\Rule)" => [
	       "store_id" => 0,
	     ],


Can you reproduce the problem with my CSV file? @wagnert

**Comment by wagnert** [comment]
Hi @amenk, did you still face the problem again or can we close the issue?

**Comment by amenk** [comment]
Cannot reproduce currently

**Comment by amenk** [comment]
Unfortunately we can now reproduce it again in our CI pipeline

**Comment by amenk** [comment]
@wagnert We can confirm the fix. Thank you very much!

**Comment by wagnert** [comment]
@amenk Thanks for the feedback, like to hear that :)
